{% set name = "s3fs-fuse" %}
{% set version = "1.96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s3fs-fuse/s3fs-fuse/archive/v{{ version }}.tar.gz
  sha256: e11a051f23701445ca99ff0bfbc4e49d8b87c66cdd04a68a1802c2613ba9e3f1

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git
    - make
    - autoconf
    - automake
    - pkg-config
  host:
    - libfuse3 >=3.0.0
    - libcurl
    - openssl
    - libxml2
    - zlib

test:
  commands:
    - s3fs --help

about:
  home: https://github.com/s3fs-fuse/s3fs-fuse
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FUSE-based file system backed by Amazon S3
  description: |
    s3fs allows Linux and macOS to mount an S3 bucket via FUSE. 
    s3fs preserves the native object format for files, allowing use of other tools like AWS CLI.
  doc_url: https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ
  dev_url: https://github.com/s3fs-fuse/s3fs-fuse

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
    - maresb
