{% set name = "s3fs-fuse" %}
{% set version = "1.92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s3fs-fuse/s3fs-fuse/archive/v{{ version }}.tar.gz
  sha256: 76ebea3c0784c5c0f6b84e009d555806aff86258886ced39eee316bf02ae8750

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - pkg-config
  host:
    - libfuse >=2.8.4,<3
    - libcurl
    - openssl
    - libxml2

test:
  commands:
    - s3fs --help

about:
  home: https://github.com/s3fs-fuse/s3fs-fuse
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FUSE-based file system backed by Amazon S3
  description: |
    s3fs allows Linux and macOS to mount an S3 bucket via FUSE. 
    s3fs preserves the native object format for files, allowing use of other tools like AWS CLI.
  doc_url: https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ
  dev_url: https://github.com/s3fs-fuse/s3fs-fuse

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
    - maresb
