{% set name = "s3fs-fuse" %}
{% set version = "1.89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s3fs-fuse/s3fs-fuse/archive/v{{ version }}.tar.gz
  sha256: 2bb9c8cad855df5a877440edac9539bd405850d2a3c366cebd9d1fec6f802e29
  patches:
    # patches from https://github.com/s3fs-fuse/s3fs-fuse/pull/1365/files
    - patches/fdcache.cpp.patch
    - patches/fdcache.h.patch
    - patches/sighandlers.cpp.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - pkg-config
  host:
    - libfuse >=2.8.4,<3
    - libcurl
    - openssl
    - libxml2

test:
  commands:
    - s3fs --help

about:
  home: https://github.com/s3fs-fuse/s3fs-fuse
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FUSE-based file system backed by Amazon S3
  description: |
    s3fs allows Linux and macOS to mount an S3 bucket via FUSE. 
    s3fs preserves the native object format for files, allowing use of other tools like AWS CLI.
  doc_url: https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ
  dev_url: https://github.com/s3fs-fuse/s3fs-fuse

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
