{% set name = "s3fs-fuse" %}
{% set version = "1.90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s3fs-fuse/s3fs-fuse/archive/v{{ version }}.tar.gz
  sha256: 75fad9560174e041b273bf510d0d6e8d926508eba2b1ffaec9e2a652b3e8afaa
  patches:
    # See https://github.com/s3fs-fuse/s3fs-fuse/issues/1590
    - patches/fdcache_entity.h.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - pkg-config
  host:
    - libfuse >=2.8.4,<3
    - libcurl
    - openssl
    - libxml2

test:
  commands:
    - s3fs --help

about:
  home: https://github.com/s3fs-fuse/s3fs-fuse
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FUSE-based file system backed by Amazon S3
  description: |
    s3fs allows Linux and macOS to mount an S3 bucket via FUSE. 
    s3fs preserves the native object format for files, allowing use of other tools like AWS CLI.
  doc_url: https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ
  dev_url: https://github.com/s3fs-fuse/s3fs-fuse

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
    - maresb
